# version: '3.8'

# services:
#   vlstorage:
#     image: victoriametrics/victoria-logs:v1.49.0
#     container_name: node-3-vlstorage
#     command:
#       - "-storageDataPath=/storage"
#       - "-retentionPeriod=1y"
#       - "-httpListenAddr=:9428"
#     volumes:
#       - ./storage:/storage
#     ports:
#       - "8003:9428"
#     deploy:
#       resources:
#         limits:
#           memory: 512M
#     restart: unless-stopped

services:
  vlstorage:
    image: victoriametrics/victoria-logs:v1.49.0
    container_name: node-3-vlstorage
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=1y"
      - "-httpListenAddr=:9428"
    volumes:
      - ./storage:/storage
    ports:
      - "8002:9428"
    restart: unless-stopped
    networks:
      - multi-node-net

networks:
  multi-node-net:
    external: true