[SERVICE]
    Flush         5
    Log_Level     info
    Daemon        Off
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name              tail
    Path              /var/log/hpc-simulator/*.log
    Tag               hpc.logs
    Refresh_Interval  5
    Mem_Buf_Limit     10MB

[OUTPUT]
    Name    kafka
    Match   hpc.*
    Brokers localhost:9092
    Topics  hpc-logs
    rdkafka.socket.keepalive.enable true
