[SERVICE]
    Flush           1
    Log_Level       info
    Parsers_File    parsers.conf

[INPUT]
    Name            tail
    Path            /tmp/hpc-simulator.log
    Parser          json
    Tag             hpc.logs
    Refresh_Interval 1
    DB              /tmp/fluent-bit-hpc.db

[OUTPUT]
    Name            kafka
    Match           hpc.*
    Brokers         localhost:9092
    Topics          hpc-logs
    Format          json
    Timestamp_Key   _time
