# version: "3.9"
services:

  generator:
    build: ./1-gen
    container_name: log-generator
    volumes:
      - ./0-logs:/logs

  fluentbit:
    image: fluent/fluent-bit:4.2.3
    container_name: fluentbit
    volumes:
      - ./0-logs:/logs
      - ./2-fluentbit/fluent-bit.conf:/fluent-bit/etc/fluent-bit.conf
      - ./2-fluentbit/parser.conf:/fluent-bit/etc/parser.conf
    command: >
      /fluent-bit/bin/fluent-bit
      -c /fluent-bit/etc/fluent-bit.conf
    depends_on:
      - generator