# services:
#   vlselect:
#     image: victoriametrics/victoria-logs:v1.49.0
#     container_name: node-4-vlselect
#     command:
#       - "-storageNode=host.docker.internal:8002"
#       - "-storageNode=host.docker.internal:8003"
#       - "-httpListenAddr=:9429"
#       - "-insert.disable=true"
#     ports:
#       - "8004:9429"
#     restart: unless-stopped

#   grafana:
#     image: grafana/grafana:11.4.0
#     container_name: node-4-grafana
#     environment:
#       GF_SECURITY_ADMIN_USER: admin
#       GF_SECURITY_ADMIN_PASSWORD: admin
#       GF_USERS_ALLOW_SIGN_UP: "false"
#       GF_INSTALL_PLUGINS: victoriametrics-logs-datasource
#     volumes:
#       - ./datasources.yml:/etc/grafana/provisioning/datasources/datasources.yml:ro
#     ports:
#       - "3001:3000"
#     depends_on:
#       - vlselect
#     restart: unless-stopped

#   vmalert:
#     image: victoriametrics/vmalert:latest
#     container_name: node-4-vmalert
#     command:
#       - "-datasource.url=http://host.docker.internal:8005"
#       - "-datasource.queryStep=30s"
#       - "-rule=/etc/alerts/alerts.yml"
#       - "-evaluationInterval=30s"
#       - "-httpListenAddr=:8880"
#       - "-notifier.url=http://alertmanager:9093"
#     volumes:
#       - ./alerts.yml:/etc/alerts/alerts.yml:ro
#     ports:
#       - "8881:8880"
#     depends_on:
#       - alertmanager
#     restart: unless-stopped

#   alertmanager:
#     image: prom/alertmanager:latest
#     container_name: alertmanager
#     volumes:
#       - ./alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro
#     command:
#       - "--config.file=/etc/alertmanager/alertmanager.yml"
#       - "--web.listen-address=:9093"
#     ports:
#       - "9095:9093" # host port 9095 -> container 9093
#     restart: unless-stopped

#     # Disable clustering to avoid gossip port conflicts in a single-node simulation


services:
  vlstorage:
    image: victoriametrics/victoria-logs:v1.49.0
    container_name: node-4-vlstorage
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=1y"
      - "-httpListenAddr=:9428"
    volumes:
      - ./storage:/storage
    ports:
      - "8003:9428"
    restart: unless-stopped
    networks:
      - multi-node-net

networks:
  multi-node-net:
    external: true