[SERVICE]
    Flush           1
    Daemon          Off
    Log_Level       info
    Parsers_File    /fluent-bit/etc/parser.conf
    storage.path    /fluent-bit/storage
    storage.sync    normal
    storage.checksum on
    storage.backlog.mem_limit 50MB

########################################################
# INPUT
########################################################

[INPUT]
    Name              tail
    Path              /logs/logs.log
    Tag               app.logs
    Parser            json_parser
    DB                /fluent-bit/tail.db
    Mem_Buf_Limit     100MB
    Skip_Long_Lines   On
    Refresh_Interval  5

########################################################
# FILTER (optional but recommended)
########################################################

[FILTER]
    Name          modify
    Match         app.logs
    Add           pipeline fluentbit
    Add           source   log-generator

########################################################
# OUTPUT
########################################################

[OUTPUT]
    Name            kafka
    Match           app.logs
    Brokers         kafka:9092
    Topics          logs
    Timestamp_Key   timestamp
    rdkafka.request.required.acks   1
    rdkafka.log.connection.close    false
    rdkafka.compression.codec   lz4
    rdkafka.batch.num.messages  1000
    rdkafka.queue.buffering.max.messages    100000
    rdkafka.linger.ms   20