input {
  kafka {
    bootstrap_servers => "localhost:9092"
    topics            => ["hpc-logs"]
    group_id          => "logstash-consumer5"
    codec             => "json"
    auto_offset_reset => "earliest"
  }
}

filter {
  mutate {
    remove_field => ["@version", "event", "tags"]
  }
}

output {
  http {
    url          => "http://localhost:9428/insert/jsonline"
    http_method  => "post"
    format       => "json"
    content_type => "application/json"
  }
}
