input {
  dead_letter_queue {
    path => "/usr/share/logstash/data/dlq"
    commit_offsets => true
    pipeline_id => "main"
  }
}

output {
  stdout { 
    codec => rubydebug 
  }
}

# docker run --rm -it \
#   -v $(pwd)/4-logstash/dlq_reader.conf:/usr/share/logstash/pipeline/logstash.conf:ro \
#   -v $(pwd)/4-logstash/dlq:/usr/share/logstash/data/dlq:ro \
#   docker.elastic.co/logstash/logstash:9.3.2 \
#   -f /usr/share/logstash/pipeline/logstash.conf