input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics => ["logs"]

    group_id => "logstash-group"
    client_id => "logstash-consumer"

    auto_offset_reset => "earliest"
    enable_auto_commit => true

    consumer_threads => 6
    decorate_events => true

    codec => json
  }
}

filter {

  mutate {
    add_field => { "ingest_stage" => "logstash" }
  }

  date {
    match => ["_time","ISO8601"]
    target => "@timestamp"
  }

  mutate {
    remove_field => ["host","@version"]
  }

}

output {

  stdout {
    codec => rubydebug
  }

  http {
    url => "http://victorialogs:9428/insert/jsonline"
    http_method => "post"
    format => "json_batch"

    pool_max => 200
    pool_max_per_route => 100

    automatic_retries => 3
    retry_failed => true
  }

}
