input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics            => ["hpc-logs"]
    group_id          => "logstash-vlogs-consumer"
    codec             => "json"
    consumer_threads  => 3
    auto_offset_reset => "earliest"
  }
}

filter {
  # _msg: use existing field from simulator, fallback to message
  if ![_msg] {
    mutate { add_field => { "_msg" => "%{message}" } }
  }

  # _time: simulator already sends it — DO NOT add again
  # Just remove Logstash internal fields
  mutate {
    remove_field => ["@version", "@timestamp", "event", "message"]
  }
}

output {
  http {
    url          => "http://victorialogs:9428/insert/jsonline"
    http_method  => "post"
    content_type => "application/stream+json"
    format       => "json"
  }
}