events {
    worker_connections 1024;
}

http {
    upstream vlselect_backend {
        least_conn;
        server host.docker.internal:8004 weight=100;
        server 127.0.0.1:8006 weight=1;
    }

    server {
        listen 9429;

        location / {
            proxy_pass http://vlselect_backend;
            proxy_http_version 1.1;
            proxy_set_header Connection "";
            proxy_set_header Host $host;
            proxy_read_timeout 30s;
            proxy_next_upstream error timeout http_500 http_502 http_503;
        }
    }
}