service:
  flush: 1
  refresh_interval: 1
  #skip_long_lines: on
  log_level: info
  parsers_file: /fluent-bit/etc/parsers.conf
  http_server: true
  http_listen: 0.0.0.0
  http_port: 2020

pipeline:
  inputs:
    - name: tail
      path: /logs/hpcm.json
      parser: json
      tag: hpc.logs
      read_from_head: true

    - name: tail
      path: /logs/monitoring.json
      parser: json
      tag: monitoring.logs
      read_from_head: true

    - name: tail
      path: /logs/syslog.json
      parser: json
      tag: syslog.logs
      read_from_head: true

  outputs:

    - name: stdout
      match: '*'
      format: json_lines

    - name: kafka
      match: '*'
      brokers: 172.29.0.10:9092
      topics: logs
      # Timestamp_Key: @timestamp