input {
  kafka {
    bootstrap_servers => "kafka:9092"
    topics            => ["hpc-logs"]
    group_id          => "logstash-consumer"
    codec             => "json"
    auto_offset_reset => "earliest"
    consumer_threads  => 6
    max_poll_records  => "500"
    decorate_events   => false
  }
}

filter {

    if [Severity] {
    mutate {
      rename => { "Severity" => "level" }
    }
  }
    mutate {
      uppercase => [ "level" ]
    }

  if [source_file]=='/generated-logs/hpcmlog.jsonl' {
    mutate { add_field => { "log_source" => "hpcmlog" } }
  } else if [source_file]=='/generated-logs/monitoring_service.jsonl' {
    mutate { add_field => { "log_source" => "monitoring" } }
  } else if [source_file]=='/generated-logs/syslog.jsonl' {
    mutate { add_field => { "log_source" => "syslog" } }
  } else if [source_file]=='/generated-logs/sample_alerting_task3.jsonl' {
    mutate { add_field => { "log_source" => "sample_alerting_task3" } }
  } else {
    mutate { add_field => { "log_source" => "dynamic_kv_ip_logs" } }
  }

  mutate {
    remove_field => [
      "@version",
      "message", "event","source",
      "source_file", "pipeline",
      "process_id"
    ]
  }
}

output {
  elasticsearch {
    hosts            => ["http://victorialogs:9428/insert/elasticsearch/"]
    http_compression => true
    parameters       => {
      "_msg_field"     => "Body"
      "_time_field"    => "@timestamp"
      "_stream_fields" => "log_source"
    }
  }
}