services:
  vlstorage:
    image: victoriametrics/victoria-logs:v1.49.0
    container_name: vl-bench-storage
    command:
      - "-storageDataPath=/storage"
      - "-retentionPeriod=1y"
      - "-httpListenAddr=:9428"
    volumes:
      - ./storage:/storage
    ports:
      - "9999:9428"
    restart: "no"